<?php

return [
    'projects' => [

        [
            'id'                => 1,
            'title'             => 'Dayussen',
            'slug'              => 'dayussen',
            'tagline'           => 'Tu tagline aquí',
            'description'       => 'Descripción corta del proyecto Dayussen.',
            'long_description'  => 'Descripción completa del proyecto Dayussen. Edita este texto en config/projects.php.',
            'category'          => 'Web Development',
            'tags'              => ['featured', 'original', 'trending'],
            'technologies'      => ['Laravel', 'PHP'],
            'year'              => 2025,
            'difficulty'        => 8,
            'status'            => 'completed',
            'rating'            => 9,
            'impact'            => 9,
            'cover_image'       => 'dayussen-cover.png',
            'preview_video'     => 'dayussen-preview.mp4',
            'demo_url'          => null,
            'github_url'        => null,
            'documentation_url' => null,
            'featured'          => true,
            'is_original'       => true,
        ],

        [
            'id'                => 2,
            'title'             => 'Taskora',
            'slug'              => 'taskora',
            'tagline'           => 'Modern task management for developers',
            'description'       => 'A sleek, developer-focused task and project management application with real-time collaboration.',
            'long_description'  => 'Taskora is a full-stack task management SaaS application designed specifically for developers and small teams. It features Kanban boards, sprint planning, time tracking, GitHub integration, and real-time collaboration powered by WebSockets.',
            'category'          => 'Web Development',
            'tags'              => ['featured', 'trending'],
            'technologies'      => ['Laravel', 'Vue.js', 'MySQL', 'Tailwind CSS'],
            'year'              => 2024,
            'difficulty'        => 8,
            'status'            => 'completed',
            'rating'            => 9,
            'impact'            => 9,
            'cover_image'       => 'taskora-cover.png',
            'preview_video'     => 'taskora-preview.mp4',
            'demo_url'          => null,
            'github_url'        => null,
            'documentation_url' => null,
            'featured'          => false,
            'is_original'       => false,
        ],

        [
            'id'                => 3,
            'title'             => 'LuziuZ',
            'slug'              => 'luziuz',
            'tagline'           => 'Tu tagline aquí',
            'description'       => 'Descripción corta del proyecto LuziuZ.',
            'long_description'  => 'Descripción completa del proyecto LuziuZ. Edita este texto en config/projects.php.',
            'category'          => 'Web Development',
            'tags'              => ['featured', 'trending'],
            'technologies'      => ['Laravel', 'PHP'],
            'year'              => 2025,
            'difficulty'        => 8,
            'status'            => 'completed',
            'rating'            => 9,
            'impact'            => 9,
            'cover_image'       => 'luziuz-cover.png',
            'preview_video'     => 'luziuz-preview.mp4',
            'demo_url'          => null,
            'github_url'        => null,
            'documentation_url' => null,
            'featured'          => false,
            'is_original'       => false,
        ],

    ],
];
